//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insect.IntegrationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insect.IntegrationTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table InsectTest.dbo.[Users]
        ///(Id int identity(1,1) not null,
        ///Username varchar(max),
        ///Salt varchar(max),
        ///MobileFor2Factor varchar(max),
        ///SecurityAnswer1 varchar(max),
        ///SecurityAnswer2 varchar(max),
        ///SecurityQuestion1 varchar(max),
        ///SecurityQuestion2 varchar(max),
        ///FailedLoginCount int,
        ///PasswordExpiryDate datetime null,
        ///UserLevel int,
        ///IsLocked bit)
        ///
        ///create table InsectTest.dbo.[Sessions]
        ///(
        ///Id int identity(1,1) not null,
        ///SessionId uniqueidentifier,
        ///UserId int,
        ///ExpiryDate datetime null,
        ///Lev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DropAndCreateDb {
            get {
                return ResourceManager.GetString("DropAndCreateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ALTER DATABASE InsectTest
        ///SET SINGLE_USER
        ///WITH ROLLBACK IMMEDIATE;
        ///ALTER DATABASE InsectTest
        ///SET MULTI_USER;
        ///
        ///
        ///DROP DATABASE InsectTest.
        /// </summary>
        internal static string SafeDropTestDb {
            get {
                return ResourceManager.GetString("SafeDropTestDb", resourceCulture);
            }
        }
    }
}
